import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { GoogleAuthProvider } from "@/providers/GoogleAuthProvider";
import { Auth0CustomProvider } from "@/providers/Auth0CustomProvider";
import { Web3authProvider } from "@/providers/web3authProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Web3authProvider>
          <GoogleAuthProvider>
            <Auth0CustomProvider>{children}</Auth0CustomProvider>
          </GoogleAuthProvider>
        </Web3authProvider>
      </body>
    </html>
  );
}
